using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

//CE SCRIPT UTILE LES TUILES POUR PERMETTRE LE D╔PLACEMENT
public class MovementOnTile : MonoBehaviour
{
    private LinkedList<Transform> _road = new LinkedList<Transform>();
    private int _indexRoadToGo;
    //-------------------------
    
    [SerializeField]
    private string _fromDirection;
    private GameObject _currentTile;
    private string _allDirectionsOfATile;
    private int _choice = 1; //ne pas mettre de choix par dķfaut fixe
    private string _goDirection = "";
    private int _indexDirection;
    private int _NORTH_INVERSION = -1; //a gķrer quand il y aura l'input system
    private Transform _nextRoad;

    //FlĶches (circle actuellement)
    public GameObject cGauche;
    public GameObject cDroit;

    //dķplacements mathķmatique
    private float _tParam;
    private Vector3 _objectPosition;
    private bool _coroutineAllowed;
    public float speed;
    private bool _reversePoints;
    private Vector3 p0;
    private Vector3 p1;
    private Vector3 p2;
    private Vector3 p3;


    // Start is called before the first frame update
    void Start()
    {
        _indexRoadToGo = 0; //pour test
        _tParam = 0f;
        _coroutineAllowed = true;
    }
    // Update is called once per frame
    void Update()
    {
        /*x = this.transform.position.x;
        y = this.transform.position.y;
        Debug.Log("x = " + x);
        Debug.Log("y = " + y);*/


        if (_coroutineAllowed)
        {
            //StartCoroutine(GoByTheRoute(_indexTileCollection));
            StartCoroutine(GoByTheRoute(_indexRoadToGo)); //pour le test
        }

        //Si l'objet possķdant le script possĶde le tag joueur
        if (this.gameObject.GetComponent<MovementOnTile>().tag == "Player")
        {
            //PLAYER INPUT (Ó retravailler) --> avant prochain aiguillage
            if (Input.GetKeyDown(KeyCode.Q))
            {
                _choice = 1;
                cGauche.GetComponent<SpriteRenderer>().color = new Color (1, 0, 0, 1);
                cDroit.GetComponent<SpriteRenderer>().color = new Color(0, 0, 0, 0);
            }
            else if (Input.GetKeyDown(KeyCode.D))
            {
                _choice = -1;
                cGauche.GetComponent<SpriteRenderer>().color = new Color(0, 0, 0, 0);
                cDroit.GetComponent<SpriteRenderer>().color = new Color(1, 0, 0, 1);
            }
        }

        if (this.gameObject.GetComponent<MovementOnTile>().tag == "Enemy")
        {
            //CODER CHOIX IA ENEMY
            _choice = 1;
        }
        Debug.Log("choix :" + _choice);
    }

    

    //rķcupĶre la tuile sur laquelle le joueur est entrain de naviguer
    private void OnTriggerEnter2D(Collider2D collider)
    {
        //vitesse : but --> faire en sorte que la vitesse reste constante malgrķ la distance
        speed = (float)(speed + 0.1);

        //Debug.Log("TUILE ACTUELLE : " + _currentTile);
        //D╔TERMINER LA DIRECTION-----------------------------------------
        //rķcupķration de la tuile actuelle
        if (collider.gameObject.CompareTag("Bullet"))//si la balle entre en collision avec le train
            return;//tu ne fais rien
        else if (collider.gameObject.CompareTag("Enemy") || collider.gameObject.CompareTag("Player"))
        {
            //animation Ó mettre
            //A VOIR S'IL SUFFIT D'UNE COLLISION POUR DETRUIRE LES TRAINS
            Destroy(this.gameObject);
        }
        //si autre chose entre en contact avec le train (attention, Ó faire ķvoluer pour la suite du jeu :
        //penser Ó crķer un prefab pour les tuile, mettre un tag et vķrifier que le parent du collider possĶde le tag "tile"
        _currentTile = collider.transform.parent.gameObject;

        _reversePoints = false;

        //Debug.Log("TUILE actuelle : " + _currentTile.name);
        _allDirectionsOfATile = PossibleDirections(_currentTile);
        //Debug.Log("Directions possibles : " + _allDirectionsOfATile);
        _indexDirection = GetIndexDirection(_allDirectionsOfATile, _fromDirection);
        //Debug.Log("ORIGINE : " + _indexDirection);
        _goDirection = GetDirection(_indexDirection, _choice, _NORTH_INVERSION, _fromDirection, _allDirectionsOfATile);
        Debug.Log("Prochaine DIRECTION : " + _goDirection);
        Debug.Log("--------------------------------------------------------------------------------");

        //D╔TERMINER LA BONNE ROUTE-----------------------------------------
        //rķcupķrer la prochaine route en fonction du nom et l'ajoute Ó la liste
        string nameNextRoad = _fromDirection + _goDirection;
        if (_currentTile.transform.Find(nameNextRoad) == null)
        {
            nameNextRoad = _goDirection + _fromDirection;
            _reversePoints = true;
        }

        Debug.Log("Nom prochaine ROUTE : " + nameNextRoad);

        _nextRoad = _currentTile.transform.Find(nameNextRoad);
        _road.AddLast(_nextRoad);

        switch (_goDirection)
        {
            case "N":
                _fromDirection = "S";
                break;
            case "E":
                _fromDirection = "O";
                break;
            case "S":
                _fromDirection = "N";
                break;
            case "O":
                _fromDirection = "E";
                break;
        }
    }



    //rķcupĶre les directions possibles
    private string PossibleDirections(GameObject actualTile)
    {
        return actualTile.GetComponent<tileManager>().directionOfTile;
    }



    //calcul index de la direction de provenance dans la liste des directions de la tuile
    private int GetIndexDirection(string allDirections, string previousDirection)
    {
        return allDirections.IndexOf(previousDirection);
    }



    //calcul index puis prochaine direction
    private string GetDirection(int index, int playerDirection, int INVERSION, string fromD, string allPossibleDirections)
    {
        //_choice (playerDirection) ne marche pas tout le temps ?
        //VERSION AVEC 2 TOUCHES
        int i = index + playerDirection; //* (fromD == "N" ? INVERSION : 1);
        return allPossibleDirections.Substring((i + allPossibleDirections.Length) % allPossibleDirections.Length, 1);
    }



    //D╔PLACEMENTS------------------------------------------------------------------------
    IEnumerator GoByTheRoute(int roadNum)
    {
        _coroutineAllowed = false;
        //rķcupķration des positions des points dans bon sens
        if (_reversePoints == true) //sens inverse
        {
            //Debug.Log("Route A inverser !");
            p0 = _road.ElementAt(roadNum).Find("p4").position;
            p1 = _road.ElementAt(roadNum).Find("p3").position;
            p2 = _road.ElementAt(roadNum).Find("p2").position;
            p3 = _road.ElementAt(roadNum).Find("p1").position;
            //Debug.Log("Route inversķe !");
        }
        else //sens dķfinit dans ķditeur
        {
            p0 = _road.ElementAt(roadNum).Find("p1").position;
            p1 = _road.ElementAt(roadNum).Find("p2").position;
            p2 = _road.ElementAt(roadNum).Find("p3").position;
            p3 = _road.ElementAt(roadNum).Find("p4").position;
        }

        while (_tParam < 1)
        {
            _tParam += Time.deltaTime * speed;

            //la position de la forme prend la valeur de la courbe
            _objectPosition = Mathf.Pow(1 - _tParam, 3) * p0 +
                              3 * Mathf.Pow(1 - _tParam, 2) * _tParam * p1 +
                              3 * (1 - _tParam) * Mathf.Pow(_tParam, 2) * p2 +
                              Mathf.Pow(_tParam, 3) * p3;


            //Rotation de la forme en fonction de la direction de la courbe
            //crķation vecteur de dķplacement (grŌce actuelle et nouvelle position) > crķation angle > rotation de l'angle en z seulement
            Vector3 dir = new Vector3(_objectPosition.x - transform.position.x, _objectPosition.y - transform.position.y, 0.0f);
            float angle = Mathf.Atan2(dir.y, dir.x) * Mathf.Rad2Deg;
            transform.rotation = Quaternion.Euler(0, 0, angle);


            //dķplacement
            transform.position = _objectPosition;

            yield return new WaitForEndOfFrame();
        }

        //MAJ des paramĶtres aprĶs le dķplacement
        _tParam = 0;
        speed = speed * 0.90f;
        _indexRoadToGo += 1;

        _coroutineAllowed = true;
    }
}
